Source/Class Project/CS461 M3 Cross Country/Models/Athlete.cs
namespace CS461_M3_Cross_Country.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Athlete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athlete()
        {
            Devices = new HashSet<Device>();
            ParentsAthletes = new HashSet<ParentsAthlete>();
            Sessions = new HashSet<Session>();
        }

        public int AthleteID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public int Age { get; set; }

        [Required]
        [StringLength(10)]
        public string Height { get; set; }

        [Required]
        [StringLength(10)]
        public string Weight { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentsAthlete> ParentsAthletes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}

Source/Class Project/CS461 M3 Cross Country/Controllers/AthletesController.cs
using CS461_M3_Cross_Country.DAL;
using CS461_M3_Cross_Country.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CS461_M3_Cross_Country.Controllers
{
    public class AthletesController : Controller
    {
        private XCDatabaseContext db = new XCDatabaseContext();

        /// <summary>
        /// Provides a list of all the athletes in the system.
        /// </summary>
        /// <returns>Returns a view containing a list of athletes.</returns>
        public ActionResult Index()
        {
            var athletes = db.Athletes.ToList();
            return View(athletes);
        }

        /// <summary>
        /// Provides a summary of an athlete.
        /// </summary>
        /// <param name="id">The identification number of the athlete.</param>
        /// <returns>A view containing the specified athlete's information.</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        /// <summary>
        /// Provides the creation tool to add a new athlete for the database.
        /// </summary>
        /// <returns>Returns a view </returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Adds a new athlete to the database.
        /// </summary>
        /// <param name="athlete">The athlete being created.</param>
        /// <returns>REsirtectToAction to the index that contains the list of athletes.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AthleteID,FirstName,LastName,Age,Height,Weight")] Athlete athlete)
        {
            try
            {
                db.Athletes.Add(athlete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Create");
            }
        }

        /// <summary>
        /// Allow the editing of an athlete in the database.
        /// </summary>
        /// <param name="id">The identification number of the athlete being edited.</param>
        /// <returns>A view containing the athlete being edited.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        /// <summary>
        /// Edits the athlete in the system
        /// </summary>
        /// <param name="athlete">The athlete being edited.</param>
        /// <returns>RedirectToAction to the list of Athletes.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AthleteID,FirstName,LastName,Age,Height,Weight")] Athlete athlete)
        {
           if(ModelState.IsValid)
            { 
                db.Entry(athlete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return RedirectToAction("Edit", athlete.AthleteID);
        }

        /// <summary>
        /// Editor that enabled the removal of an athlete from the system.
        /// </summary>
        /// <param name="id">The identification number of the athlete.</param>
        /// <returns>A view containing the athlete that is going to be removed.</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        /// <summary>
        /// Deletes the specified athlete from the system.
        /// </summary>
        /// <param name="id">The identification number of the athlete to remove.</param>
        /// <returns>REdirectToAction send the user to the list of athletes when complete.</returns>
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if(ModelState.IsValid)
            { 
                Athlete athlete = db.Athletes.Find(id);
                db.Athletes.Remove(athlete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return RedirectToAction("Delete", id);
        }

        public ActionResult Login()
        {
            var athletes = db.Athletes.ToList();
            return View(athletes);
        }

        public ActionResult AthleteDetails(int id)
        {
            
            Athlete athlete = db.Athletes.Find(id);
            ViewBag.AthleteName = athlete.FirstName + " " + athlete.LastName;
            ViewBag.AthleteID = athlete.AthleteID;

            var sessions = db.Sessions.Where(s => s.AthleteID == athlete.AthleteID).ToList();
            return View(sessions);
        }

        /// <summary>
        /// Get the session speed information for the specified athlete.
        /// </summary>
        /// <param name="id">The database identification number of the athlete.</param>
        /// <returns></returns>
        public JsonResult AthleteSpeeds(int id)
        {
            var sessions = db.Sessions.Where(s => s.Athlete.AthleteID == id).ToList();
            List<Speed> speeds = new List<Speed>();
            // For each item in the query create a new speed item.
            foreach (var item in sessions)
            {
                Speed speed = new Speed();
                speed.Date = item.TrainingDate.ToShortDateString();
                speed.Distance = item.Distance;
                speed.Time = item.TrainingTime;
                // Add the speed item to the list of speeds for that athlete.
                speeds.Add(speed);
            }
            
            return Json(speeds, JsonRequestBehavior.AllowGet);
        }
    }
}

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/AthleteDetails.cshtml
@model IEnumerable<CS461_M3_Cross_Country.DAL.Session>
@{
    ViewBag.Title = ViewBag.AthleteName + " Details";
}
<h2 class="display-4">@ViewBag.AthleteName</h2>
<h3>Distance Data</h3>
<table class="table table-hover table-responsive-lg">
    <tr class="table-primary">
        <th>@Html.DisplayNameFor(model => model.TrainingDate)</th>
        <th>@Html.DisplayNameFor(model => model.Distance)</th>
        <th>Difference</th>
    </tr>
    @{
        var i = 0;
        foreach (var session in Model)
        {
            if (i == 0)
            {
                ViewBag.Last = session.Distance;
                <tr>
                    <td>@Html.DisplayFor(modelItem => session.TrainingDate)</td>
                    <td>@Html.DisplayFor(modelItem => session.Distance)</td>
                    <td>n/a</td>
                </tr>
                i++;
            }
            else
            {
                ViewBag.Difference = session.Distance - ViewBag.Last;
                <tr>
                    <td>@Html.DisplayFor(modelItem => session.TrainingDate)</td>
                    <td>@Html.DisplayFor(modelItem => session.Distance)</td>
                    @if (ViewBag.Difference > 0)
                    {
                        <td class="text-success">+@ViewBag.Difference</td>
                    }
                    else
                    {
                        <td class="text-danger">@ViewBag.Difference</td>
                    }
                </tr>
                ViewBag.Last = session.Distance;
            }

        }
    }
</table>
<br />
@* Start of the athlete speed data section. *@
<h3>Speed Data</h3>
@* This div will be populated with the information from the runs relevant to the current student. *@
<div id="speed-graph">
    <canvas id="myChart" width="850" height="420" style="width: 876px; height: 438px"></canvas>
</div>
<div id="speed-table"></div>



@{ 
    // Get the data from the session and use it to create labels and data sets
    // the the charts.
    string sessionStrings = "";
    string sessionSpeeds = "";
    double maxSpeed = double.NegativeInfinity;
    // for each session in the model.
    foreach(var session in Model)
    {
        // Get the training data for the label,
        sessionStrings += " ";
        sessionStrings += ",";
        double thisSpeed = (Math.Round((session.Distance * (1609.344) / session.TrainingTime.TotalSeconds), 2));
        if (thisSpeed > maxSpeed) { maxSpeed = thisSpeed; }
        // Get the speed of the athlete for that session.
        sessionSpeeds +=  thisSpeed.ToString() + ",";
    }
    maxSpeed += 0.01;
}

@section PageScripts
{
    @* Adds the CDN for chart.js *@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>
    <script>
        // max speed of this athlete
        maxSpeed = null;
        // When the document is loaded 
        $(function () {
            $.ajax(
                {
                    type: 'GET',
                    dataType: 'json',
                    url: '/Athletes/AthleteSpeeds/@((Model.FirstOrDefault() == null)? 0 : Model.FirstOrDefault().AthleteID)',
                    success: function (data) { displayData(data); },
                    error: function () { ajaxError(); }
                }
            );
        });
        
        // Place the data into a table
        function displayData(data) {
            var string = '<table class="table table-hover table-responsive-lg"'
                //+ 'style="width:90%; margin: 0px auto;">'
                + '<thead><tr class="table-primary">'
                + '<th>Date</th>'
                + '<th>Distance</th>'
                + '<th>Average Speed</th></tr></thead><tbody>';
            // The previous speed is equal to the max float.
            previousSpeed = null;
            
            $.each(data, function (i, item) {
                string += '<tr><td>'
                    + item['Date']
                    + '</td><td>'
                    + item['Distance']
                    + '</td>'
                    + ((previousSpeed == null)
                        ? '<td>'
                        : (item['AverageSpeed'] < previousSpeed)
                            ? '<td class="text-danger">'
                            : '<td class="text-success">')
                    + item['AverageSpeed']
                    + " m/s"
                    + '</td></tr>';
                previousSpeed = item['AverageSpeed'];
                maxSpeed = (maxSpeed == null)
                    ? item['AverageSpeed']
                    : (item['AverageSpeed'] > maxSpeed)
                        ? item['AverageSpeed']
                        : maxSpeed;
            });
            string += '</tbody></table>';
            $('#speed-table').append(string);
        }
        
        // Something bad happened. Let the user know
        function ajaxError() {
            alert("Warning: Unable to recieve speed data. Please try again later.");
        }
        maxSpeed += 0.03
        var ctx = document.getElementById('myChart').getContext('2d');
        var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'line',

            // The data for our dataset
            data: {
                labels: [@sessionStrings],
                datasets: [{
                    label: "Session Speeds",
                    backgroundColor: 'rgba(0, 0, 0, 0)',
                    borderColor: 'rgb(89, 49, 150)',
                    data: [@sessionSpeeds],
                }]
            },
            // Configuration options go here
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            suggestedMin: 0,
                            suggestedMax: @maxSpeed.ToString()
                        }
                    }]
                }
            }
        });
    </script>
}

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/Create.cshtml
@model CS461_M3_Cross_Country.DAL.Athlete
@{
    ViewBag.Title = "Add Athlete";
}

<h2>Add Athlete</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Athlete Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Athletes List", "Index")
</div>

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/Delete.cshtml
@model CS461_M3_Cross_Country.DAL.Athlete

@{
    ViewBag.Title = "Delete Athlete";
}

<h2>Delete Athlete</h2>

<h3>Are you sure you want to delete this Athlete?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Athletes List", "Index")
        </div>
    }
</div>

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/Details.cshtml
@model CS461_M3_Cross_Country.DAL.Athlete

@{
    ViewBag.Title = "Athlete Details";
}

<h2>Athlete Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AthleteID }) |
    @Html.ActionLink("Athletes List", "Index")
</p>

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/Edit.cshtml
@model CS461_M3_Cross_Country.DAL.Athlete

@{
    ViewBag.Title = "Edit Athlete";
}

<h2>Edit Athlete</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AthleteID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Athletes List", "Index")
</div>

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/Index.cshtml
@model IEnumerable<CS461_M3_Cross_Country.DAL.Athlete>

@{
    ViewBag.Title = "Athlete List";
}

<h2>Athlete List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover">
    <tr class="table-primary">
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

    @foreach (var athlete in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => athlete.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => athlete.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => athlete.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => athlete.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => athlete.Weight)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = athlete.AthleteID }) |
                @Html.ActionLink("Details", "Details", new { id = athlete.AthleteID }) |
                @Html.ActionLink("Delete", "Delete", new { id = athlete.AthleteID })
            </td>
        </tr>
    }
</table>

Source/Class Project/CS461 M3 Cross Country/Views/Athletes/Login.cshtml
@model IEnumerable<CS461_M3_Cross_Country.DAL.Athlete>

@{
    ViewBag.Title = "Athlete Login";
}

<h2>Login</h2>

<table class="table table-hover">
    <tr class="table-primary">
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>

        </th>
    </tr>
    @foreach (var athlete in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => athlete.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => athlete.LastName)
            </td>
            <td>
                @Html.ActionLink("Login", "AthleteDetails", "Athletes", new { id = athlete.AthleteID }, null)
            </td>
        </tr>
    }
</table>