Source/Class Project/CS461 M3 Cross Country/Controllers/ParentsController.cs
using CS461_M3_Cross_Country.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CS461_M3_Cross_Country.Controllers
{
    public class ParentsController : Controller
    {
        private XCDatabaseContext db = new XCDatabaseContext();
        // GET: Parents
        public ActionResult Index()
        {
            // send parent data for temp psuedo-login links for work prior to authentication is added.
            var parents = db.Parents.ToList();
            return View(parents);
        }

        // GET: Parents/ParentHome/{ParentID}
        // Using the parent id generate a homepage for parents to view the stats of their child(ren) (athlete(s))
        // This method will become the method for the parent index view when authentication is added and proven functional.
        public ActionResult ParentHome(int id)
        {
            // Just a quick way to send the parent name over to the view and still send athlete data with the view (obviously this would get refactored to a ViewModel later on).
            // However, the viewbag is being used to prove the arcitecture simply.
            ViewBag.ParentName = db.Parents.Where(p => p.ParentID == id).Select(ps => ps.FirstName).FirstOrDefault().ToString() + " " + 
                db.Parents.Where(pw => pw.ParentID == id).Select(ps => ps.LastName).FirstOrDefault().ToString();

            // Get The Parent's Athletes' data
            var athleteIDs = db.ParentsAthletes.Where(w => w.ParentID == id).Select(s => s.AthleteID).ToList();
            var athletes = new List<Athlete>();
            foreach(int aID in athleteIDs)
            {
                var athlete = db.Athletes.Where(a => a.AthleteID == aID).FirstOrDefault();
                athletes.Add(athlete);
            }
            
            return View(athletes);
        }

        // GET: Parents/AthleteSessions/{AthleteID}
        // This method processes data about an individual athlete sessions (related to the parent).
        // The View will be spilt into tables for Performance Metrics and Attendance Dates/Times to make it easier for a parent to make sense of the data.
        // Since there is no real authentication yet there is no way to prevent parents from seeing other athlete data (not related to them)
        // if they know how to leverage the routes.
        public ActionResult AthleteSessions(int id)
        {
            ViewBag.AthleteName = db.Athletes.Where(w => w.AthleteID == id).Select(s => s.FirstName).FirstOrDefault() + " " + db.Athletes.Where(w => w.AthleteID == id).Select(s => s.LastName).FirstOrDefault();
            var sessions = db.Sessions.Where(a => a.AthleteID == id).OrderByDescending(x => x.TrainingDate).ToList();
            return View(sessions);
        }
    }
}

Source/Class Project/CS461 M3 Cross Country/Controllers/SessionController.cs
using CS461_M3_Cross_Country.DAL;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CS461_M3_Cross_Country.Controllers
{
    public class SessionController : Controller
    {
        private XCDatabaseContext db = new XCDatabaseContext();

        // GET: Coaches
        public ActionResult Index()
        {
            var sessions = db.Sessions.ToList();
            return View(sessions);
        }


        // GET: Athletes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }
        
        // GET: Athletes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        // POST: Athletes/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {
                Session session = db.Sessions.Find(id);
                db.Sessions.Remove(session);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete", id);
        }
    }
}

Source/Class Project/CS461 M3 Cross Country/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CS461_M3_Cross_Country.Controllers
{
    public class UploadController : Controller
    {
        // GET: /
        // GET: /Index
        // GET: Upload
        public ActionResult Index(int? id)
        {
            if (id == 1)
            {
                ViewBag.Message = "File uploaded Successfully!";
            }
            return View();
        }

        // POST: Upload
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                    // Don't allow it to save the file, toss it for now since we don't have storage
                    //file.SaveAs(_path);
                }
                //ViewBag.Message = "File uploaded Successfully!";
                //return View();
                return RedirectToAction("Uploading");
            }
            catch
            {
                ViewBag.Message = "File upload FAILED!";
                return View();
            }
        }

        // GET: Uploading
        [HttpGet]
        public ActionResult Uploading()
        {
            return View();
        }
    }
}

Source/Class Project/CS461 M3 Cross Country/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cross Country Tracker</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
        @Html.ActionLink("Cross Country Tracker", "Index", "Home", null, new { @class = "navbar-brand" })
        <button class="navbar-toggler" aria-expanded="false" aria-controls="navbarColor01" aria-label="Toggle navigation" type="button" data-target="#navbarColor01" data-toggle="collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="admin" href="#" data-toggle="dropdown">Admin<span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="admin">
                        @Html.ActionLink("Devices", "Index", "Devices", null, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="coach" href="#" data-toggle="dropdown">Coach<span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="coach">
                        @Html.ActionLink("Devices", "CoachDevices", "Devices", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Athletes", "Index", "Athletes", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Sessions", "Index", "Session", null, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="athlete" href="#" data-toggle="dropdown">Athlete<span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="athlete">
                        @Html.ActionLink("Login", "Login", "Athletes", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Upload a Session", "Index", "Upload", null, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Parent", "Index", "Parents", null, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cross Country Tracker</p>
        </footer>
    </div>


    @*Long running scripts load last *@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*Optional section that laods some sections from other page. *@
    @RenderSection("PageScripts", required: false)
</body>
</html>